language: node_js
node_js: 8
cache:
  yarn: false
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: false
  on:
    branch: master
  project: hoverboard-master
  token:
    secure: QZ8AK7RT7QFkGzVSoSV5b89Qym9hJy+oGDe4aOmAQJu5+DkiWfA60p0bT8v4IqpGJXyHeLGqpoUtQjyD+/vkPs7cuda0g2sisfA2ejDhXNoCzlIQ+43xacbL0SvaXF7VE2I+HcXqCyW96BqFeMyQoPYCTT96zMMW48XUjle1C74aeaUiADJZ4cpiz4su51+rWMJx57EiE3tnFrJxgWMJK2tbXB5Nv9bgesywboEXzC67sGD6U5ONaewoztm936HW5MUvzak9AIVskD3CgkwcjtDNB8dekmJyq89gR596cEvmziOz74u8NJdV0vvPOa1bbrDY/kk8vJyQ4aeAY0vbZlUdvSf4md73GtLwYIaD+RkYvWE+9mxB7tA4/4dwcWB3RRG0qQJz3DkNys2J95EAAqGnB8Q40/QR/0AUx6FD2fe+ZhFCew1EgQyr4iQHh58Ty+LdNR3afsxP1QEhrTl/aVfbL9WNS0BkN/uhKn2o763+Z7OOklPk0/aIEDYPbRjpI3157kD+YtX/3IZRcePCEGatjEinsul5leGbcszr6IOGh1NCkHxNgK2NLGIR87F5LuGvvqE5dnu9epQn0uAQZTxPD9OwfwdRI8W1qFbf/IrPsNk4W3dl2MOfrZ2jB8vfkiNY7fpw0xaIvZsT1m1rdX2xnmsceOcEAsm2R5GHgHE=
- provider: firebase
  skip_cleanup: false
  on:
    branch: develop
  project: hoverboard-dev
  token:
    secure: QZ8AK7RT7QFkGzVSoSV5b89Qym9hJy+oGDe4aOmAQJu5+DkiWfA60p0bT8v4IqpGJXyHeLGqpoUtQjyD+/vkPs7cuda0g2sisfA2ejDhXNoCzlIQ+43xacbL0SvaXF7VE2I+HcXqCyW96BqFeMyQoPYCTT96zMMW48XUjle1C74aeaUiADJZ4cpiz4su51+rWMJx57EiE3tnFrJxgWMJK2tbXB5Nv9bgesywboEXzC67sGD6U5ONaewoztm936HW5MUvzak9AIVskD3CgkwcjtDNB8dekmJyq89gR596cEvmziOz74u8NJdV0vvPOa1bbrDY/kk8vJyQ4aeAY0vbZlUdvSf4md73GtLwYIaD+RkYvWE+9mxB7tA4/4dwcWB3RRG0qQJz3DkNys2J95EAAqGnB8Q40/QR/0AUx6FD2fe+ZhFCew1EgQyr4iQHh58Ty+LdNR3afsxP1QEhrTl/aVfbL9WNS0BkN/uhKn2o763+Z7OOklPk0/aIEDYPbRjpI3157kD+YtX/3IZRcePCEGatjEinsul5leGbcszr6IOGh1NCkHxNgK2NLGIR87F5LuGvvqE5dnu9epQn0uAQZTxPD9OwfwdRI8W1qFbf/IrPsNk4W3dl2MOfrZ2jB8vfkiNY7fpw0xaIvZsT1m1rdX2xnmsceOcEAsm2R5GHgHE=
