language: node_js
node_js: 8
cache:
  yarn: false
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: false
  on:
    branch: master
  project: devfestlk18
  token:
    secure: i5hxQD3zJ6XPIk+aINIKU7hTwTxguHlxDmK1ObqOsOQaa+smPppT185QN3ZHl1Pf92zpeGcDNVvofUAKgwfrirZ/MBsn4rrUHn3EFmX2+6N19X7pfiDx5ihnGO3eQMznRS/v9lHOojly1Lvt5QpHj6JxxlFX29S11s8F87noThUdgJIgHpN3pLXTBexGU6nw8VFYziavAJjwGIS1yVZmDhZg+C3b/3okhKlnwbYeVU+H0ec6DW0LRRzFAOQQzurj0dpwHl4sPce7+u4qS+Jblit55HGRMuwFk0kS995FrSetm09fD3biRbdEAO0sz61YFdzYW0GwKkr7CZBInjMazHRA/ppo4FOJwahtyO3T4iEPqghVvVndNF/S+EL7VsMe9dlh44umO7xzSYPliGY+aVct5aoM5NSgXR7oNPiRJIRtGXM/FML6JROJI8mtVvCJiMxxpekPdzhBK1L+gzuGJbXqpHKYcSS/LGLn3OVwzFBisVWL5goK0JKxOJcNZozlY1IPrCgpJyEwbwwAE+Let85ZrjVE3SLxDjfvBHd7cRGbHlJCo1DlqqE9Q5r0ykYHc/uvCaOu1MaxJNj1Mm8FWW+Ubq5HiFQ+DWPQwejMj+YXJk8WXs9PF6bPI89acEtHEa00dlDSxvc9DfAz5xl4Bb5VTB4FX30x16baOFKzNaU=
- provider: firebase
  skip_cleanup: false
  on:
    branch: develop
  project: devfestlk18
  token:
    secure: Qi5hxQD3zJ6XPIk+aINIKU7hTwTxguHlxDmK1ObqOsOQaa+smPppT185QN3ZHl1Pf92zpeGcDNVvofUAKgwfrirZ/MBsn4rrUHn3EFmX2+6N19X7pfiDx5ihnGO3eQMznRS/v9lHOojly1Lvt5QpHj6JxxlFX29S11s8F87noThUdgJIgHpN3pLXTBexGU6nw8VFYziavAJjwGIS1yVZmDhZg+C3b/3okhKlnwbYeVU+H0ec6DW0LRRzFAOQQzurj0dpwHl4sPce7+u4qS+Jblit55HGRMuwFk0kS995FrSetm09fD3biRbdEAO0sz61YFdzYW0GwKkr7CZBInjMazHRA/ppo4FOJwahtyO3T4iEPqghVvVndNF/S+EL7VsMe9dlh44umO7xzSYPliGY+aVct5aoM5NSgXR7oNPiRJIRtGXM/FML6JROJI8mtVvCJiMxxpekPdzhBK1L+gzuGJbXqpHKYcSS/LGLn3OVwzFBisVWL5goK0JKxOJcNZozlY1IPrCgpJyEwbwwAE+Let85ZrjVE3SLxDjfvBHd7cRGbHlJCo1DlqqE9Q5r0ykYHc/uvCaOu1MaxJNj1Mm8FWW+Ubq5HiFQ+DWPQwejMj+YXJk8WXs9PF6bPI89acEtHEa00dlDSxvc9DfAz5xl4Bb5VTB4FX30x16baOFKzNaU=
